vue_basic_homepage:
    path:     /
    defaults: { _controller: "VueBundle:VueBasic:index"}

vue_basic_example1:
    path:     /example-1
    defaults: { _controller: "VueBundle:VueBasic:example1"}

vue_basic_example2:
    path:     /example-2
    defaults: { _controller: "VueBundle:VueBasic:example2"}

vue_basic_example3:
    path:     /example-3
    defaults: { _controller: "VueBundle:VueBasic:example3"}

vue_basic_example4:
    path:     /example-4
    defaults: { _controller: "VueBundle:VueBasic:example4"}

vue_basic_example5:
    path:     /example-5
    defaults: { _controller: "VueBundle:VueBasic:example5"}

vue_basic_example6:
    path:     /example-6
    defaults: { _controller: "VueBundle:VueBasic:example6"}

vue_basic_example7:
    path:     /example-7
    defaults: { _controller: "VueBundle:VueBasic:example7"}

vue_basic_example8:
    path:     /example-8
    defaults: { _controller: "VueBundle:VueBasic:example8"}

vue_basic_example9:
    path:     /example-9
    defaults: { _controller: "VueBundle:VueBasic:example9"}

vue_basic_example10:
    path:     /example-10
    defaults: { _controller: "VueBundle:VueBasic:example10"}

vue_basic_example11:
    path:     /example-11
    defaults: { _controller: "VueBundle:VueBasic:example11"}

vue_basic_example12:
    path:     /example-12
    defaults: { _controller: "VueBundle:VueBasic:example12"}

vue_basic_example13:
    path:     /example-13
    defaults: { _controller: "VueBundle:VueBasic:example13"}

vue_basic_example14:
    path:     /example-14
    defaults: { _controller: "VueBundle:VueBasic:example14"}

vue_basic_example15:
    path:     /example-15
    defaults: { _controller: "VueBundle:VueBasic:example15"}

vue_basic_example16:
    path:     /example-16
    defaults: { _controller: "VueBundle:VueBasic:example16"}

vue_basic_example17:
    path:     /example-17
    defaults: { _controller: "VueBundle:VueBasic:example17"}

vue_basic_example18:
    path:     /example-18
    defaults: { _controller: "VueBundle:VueBasic:example18"}

vue_basic_example19:
    path:     /example-19
    defaults: { _controller: "VueBundle:VueBasic:example19"}
    
vue_basic_example20:
    path:     /example-20
    defaults: { _controller: "VueBundle:VueBasic:example20"}

vue_basic_example21:
    path:     /example-21
    defaults: { _controller: "VueBundle:VueBasic:example21"}

vue_basic_example22:
    path:     /example-22
    defaults: { _controller: "VueBundle:VueBasic:example22"}

vue_basic_example23:
    path:     /example-23
    defaults: { _controller: "VueBundle:VueBasic:example23"}

vue_basic_example24:
    path:     /example-24
    defaults: { _controller: "VueBundle:VueBasic:example24"}

vue_basic_example25:
    path:     /example-25
    defaults: { _controller: "VueBundle:VueBasic:example25"}

vue_basic_example26:
    path:     /example-26
    defaults: { _controller: "VueBundle:VueBasic:example26"}