blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: en|pl
    defaults:
        _locale: '%locale%'
        
homepage:
    path: /{_locale}
    requirements:
        _locale: en|pl
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    default/homepage.html.twig
        _locale:     '%locale%'