tutorial:
    resource: "@TutorialBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/tutorial

bootstrap:
    resource: "@BootstrapBundle/Resources/config/routing.yml"
    prefix:   /bootstrap

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: en|pl|ru
    defaults:
        _locale: '%locale%'
        
homepage:
    path: /{_locale}
    requirements:
        _locale: en|pl|ru
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    start/index.html.twig
        _locale:     '%locale%'