vue_homepage:
    path:     /
    defaults: { _controller: VueBundle:Start:index }

vue_basic:
    resource: "@VueBundle/Resources/config/routing/vue_basic.yml"
    prefix:   /basic

vue_advanced:
    resource: "@VueBundle/Controller/VueAdvancedController.php"
    type:     annotation
    prefix:   /advanced

# vue_laracast:
#     resource: "@VueBundle/Resources/config/routing/vue_laracast.yml"
#     prefix:   /laracast

# vue_vuetify:
#     resource: "@VueBundle/Resources/config/routing/vue_vuetify.yml"
#     prefix:   /vuetify
